name: Auto Sync to Gitee

on:
  schedule:
    # 每天北京时间早上 8 点自动同步一次
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动点击运行

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repo to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/openclaw
          dst: gitee/openclawcn
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "openclaw"
          force_update: true
          debug: true
          clone_style: "https"
          # 注意：删除了不支持的 depth 参数
          timeout: '3h'       # 既然 1.5 小时不够，我们直接给到 3 小时上限
          lfs: true           # 开启大文件支持
